"""
LangGraph State Definitions
---------------------------
Typed state definitions for each graph layer.
This is the foundation of Goodhart-proof isolation in LangGraph.
"""

import operator
from typing import Annotated, Any, Literal, TypedDict

from typing_extensions import NotRequired

from contracts import CodeArtifact, TaskInput, Verdict, VerificationRubric


class GraphState(TypedDict):
    """
    Global graph state.
    Passed between nodes and persisted in checkpoints.
    """

    # Input
    user_spec_path: str
    feature_name: str

    # Planning output
    task: NotRequired[TaskInput]
    plan_output: NotRequired[dict]
    rubric: NotRequired[VerificationRubric]  # Generated by planning, consumed by verification. NEVER passed to execution.

    # Tier / Complexity (from task spec metadata)
    tier: NotRequired[str]       # "standard" | "adversarial" | "swe_bench"
    complexity: NotRequired[str]  # "low" | "medium" | "high"

    # Context Routing (Dynamic Budget)
    context_budget: NotRequired[dict]  # Budget allocation + compression stats from context_router

    # Model Router (Dynamic Model Selection)
    execution_config: NotRequired[dict]  # Model config from model_router: {model, base_url, max_tokens, ...}

    # Static Gate (Pre-Verification)
    static_gate_passed: NotRequired[bool]  # True = proceed to verification
    feedback: NotRequired[str]  # Abstract feedback from static gate (if failed)

    # Execution/Verification loop
    iteration: Annotated[int, operator.add]
    artifacts: Annotated[list[CodeArtifact], operator.add]
    verdicts: Annotated[list[Verdict], operator.add]
    feedback: NotRequired[str]

    # Wave management
    current_wave: NotRequired[int]
    completed_tasks: NotRequired[list[str]]
    pending_approval: NotRequired[list[dict]]
    verification_pending: NotRequired[list[str]]

    # Optimization
    optimization_report: NotRequired[str]
    aggregated_verdicts: NotRequired[list[Verdict]]
    metrics_summary: NotRequired[dict[str, Any]]
    consistency_score: NotRequired[float]

    # Final result
    final_passed: NotRequired[bool]
    total_cost: NotRequired[float]

    # Metadata
    thread_id: str
